services:
    linkfloyd_api.command.create_oauth_client_command:
        class: Linkfloyd\Bundle\ApiBundle\Command\CreateOauthClientCommand
        tags:
            - { name: console.command }
        arguments: ["@fos_oauth_server.client_manager"]
