fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /comment_api
    defaults: { _format: html }

linkfloyd_core:
    resource: "@LinkfloydCoreBundle/Resources/config/routing.yml"
    prefix:   /

linkfloyd_api:
    resource: "@LinkfloydApiBundle/Controller"
    type: annotation
    defaults: {_format: json}
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"