homepage:
    path:     /
    defaults: { _controller: LinkfloydCoreBundle:Default:index }

core_bundle_post_index:
    path:     /posts
    defaults: { _controller: LinkfloydCoreBundle:Post:index }

core_bundle_post_insert:
    path:     /posts/insert
    defaults: { _controller: LinkfloydCoreBundle:Post:insertPost }

core_bundle_post_delete:
    path:     /posts/{id}/delete
    defaults: { _controller: LinkfloydCoreBundle:Post:deletePost }
