services:
    linkfloyd.frontend.service.link_service:
        class: Linkfloyd\Bundle\CoreBundle\Service\LinkService
        arguments: ["@doctrine.orm.entity_manager"]

    linkfloyd.frontend.service.media_service:
        class: Linkfloyd\Bundle\CoreBundle\Service\MediaService
        arguments: ["@doctrine.orm.entity_manager"]
