services:
  linkfloyd.frontend.service.link_detail_service:
    class: Linkfloyd\Bundle\CoreBundle\Service\LinkDetailService
    arguments: ["@doctrine.orm.entity_manager"]

  linkfloyd.frontend.service.post_service:
    class: Linkfloyd\Bundle\CoreBundle\Service\PostService
    arguments: ["@doctrine.orm.entity_manager","@event_dispatcher"]

  linkfloyd.frontend.service.post_detail_service:
    class: Linkfloyd\Bundle\CoreBundle\Service\PostDetailService
    arguments: ["@doctrine.orm.entity_manager"]

  linkfloyd.frontend.service.media_service:
    class: Linkfloyd\Bundle\CoreBundle\Service\MediaService
    arguments: ["@doctrine.orm.entity_manager"]

  linkfloyd.frontend.service.url_service:
    class: Linkfloyd\Bundle\CoreBundle\Service\UrlService
    arguments: ["@guzzle.client", "%shibby.iframely.apikey%"]

  linkfloyd.frontend.service.post.create_post_service:
    class: Linkfloyd\Bundle\CoreBundle\Service\Post\CreatePostService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@linkfloyd.frontend.service.media_service"
      - "@linkfloyd.frontend.service.link_detail_service"
      - "@linkfloyd.frontend.service.post_service"

  linkfloyd.voter.post_voter:
    class: Linkfloyd\Bundle\CoreBundle\Security\PostVoter
    tags:
      - { name: security.voter }
    public: false

  #Event Listeners
  linkfloyd.event_listener.post_comment_count_listener:
    class: Linkfloyd\Bundle\CoreBundle\EventListener\PostCommentCountListener
    arguments: ['@linkfloyd.frontend.service.post_service']
    tags:
      - { name: kernel.event_listener, event: 'fos_comment.comment.post_persist', method: 'onCommentPostPersist'}

  guzzle.client:
    class: GuzzleHttp\Client
